// RSS feeds ingested by /api/ingest-rss. Every entry was verified to return
// items (from a cloud sandbox, Oct 2026) -- outlets that block bots or 404
// were left out. `country` is the outlet's home country, which is what the
// Off-Lens coverage bar counts. Feeds break over time: when the ingest run
// reports a feed failing repeatedly, fix its URL or drop it here.
export type RssFeed = { domain: string; country: string; url: string };

export const RSS_FEEDS: RssFeed[] = [
  { domain: "bbc.com", country: "United Kingdom", url: "http://feeds.bbci.co.uk/news/world/rss.xml" },
  { domain: "bbc.com", country: "United Kingdom", url: "https://feeds.bbci.co.uk/news/world/asia/rss.xml" },
  { domain: "bbc.com", country: "United Kingdom", url: "https://feeds.bbci.co.uk/news/world/middle_east/rss.xml" },
  { domain: "bbc.com", country: "United Kingdom", url: "https://feeds.bbci.co.uk/news/world/africa/rss.xml" },
  { domain: "bbc.com", country: "United Kingdom", url: "https://feeds.bbci.co.uk/news/world/europe/rss.xml" },
  { domain: "bbc.com", country: "United Kingdom", url: "https://feeds.bbci.co.uk/news/world/latin_america/rss.xml" },
  { domain: "theguardian.com", country: "United Kingdom", url: "https://www.theguardian.com/world/rss" },
  { domain: "independent.co.uk", country: "United Kingdom", url: "https://www.independent.co.uk/news/world/rss" },
  { domain: "skynews.com", country: "United Kingdom", url: "https://feeds.skynews.com/feeds/rss/world.xml" },
  { domain: "ft.com", country: "United Kingdom", url: "https://www.ft.com/world?format=rss" },
  { domain: "economist.com", country: "United Kingdom", url: "https://www.economist.com/international/rss.xml" },
  { domain: "middleeasteye.net", country: "United Kingdom", url: "https://www.middleeasteye.net/rss" },
  { domain: "nytimes.com", country: "United States", url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml" },
  { domain: "cnn.com", country: "United States", url: "http://rss.cnn.com/rss/edition_world.rss" },
  { domain: "foxnews.com", country: "United States", url: "https://moxie.foxnews.com/google-publisher/world.xml" },
  { domain: "cbsnews.com", country: "United States", url: "https://www.cbsnews.com/latest/rss/world" },
  { domain: "abcnews.go.com", country: "United States", url: "https://abcnews.go.com/abcnews/internationalheadlines" },
  { domain: "nbcnews.com", country: "United States", url: "https://feeds.nbcnews.com/nbcnews/public/world" },
  { domain: "politico.com", country: "United States", url: "https://rss.politico.com/politics-news.xml" },
  { domain: "thehill.com", country: "United States", url: "https://thehill.com/policy/international/feed/" },
  { domain: "foreignpolicy.com", country: "United States", url: "https://foreignpolicy.com/feed/" },
  { domain: "voanews.com", country: "United States", url: "https://www.voanews.com/api/zq$omekvi_" },
  { domain: "axios.com", country: "United States", url: "https://api.axios.com/feed/" },
  { domain: "cbc.ca", country: "Canada", url: "https://www.cbc.ca/webfeed/rss/rss-world" },
  { domain: "globalnews.ca", country: "Canada", url: "https://globalnews.ca/world/feed/" },
  { domain: "abc.net.au", country: "Australia", url: "https://www.abc.net.au/news/feed/2942460/rss.xml" },
  { domain: "smh.com.au", country: "Australia", url: "https://www.smh.com.au/rss/world.xml" },
  { domain: "theage.com.au", country: "Australia", url: "https://www.theage.com.au/rss/world.xml" },
  { domain: "rnz.co.nz", country: "New Zealand", url: "https://www.rnz.co.nz/rss/world.xml" },
  { domain: "nzherald.co.nz", country: "New Zealand", url: "https://www.nzherald.co.nz/arc/outboundfeeds/rss/section/world/?outputType=xml" },
  { domain: "aljazeera.com", country: "Qatar", url: "https://www.aljazeera.com/xml/rss/all.xml" },
  { domain: "arabnews.com", country: "Saudi Arabia", url: "https://www.arabnews.com/rss.xml" },
  { domain: "thenationalnews.com", country: "United Arab Emirates", url: "https://www.thenationalnews.com/arc/outboundfeeds/rss/?outputType=xml" },
  { domain: "jpost.com", country: "Israel", url: "https://www.jpost.com/rss/rssfeedsheadlines.aspx" },
  { domain: "haaretz.com", country: "Israel", url: "https://www.haaretz.com/srv/haaretz-latest-headlines" },
  { domain: "presstv.ir", country: "Iran", url: "https://www.presstv.ir/rss.xml" },
  { domain: "egyptindependent.com", country: "Egypt", url: "https://egyptindependent.com/feed/" },
  { domain: "dailynewsegypt.com", country: "Egypt", url: "https://www.dailynewsegypt.com/feed/" },
  { domain: "thehindu.com", country: "India", url: "https://www.thehindu.com/news/international/feeder/default.rss" },
  { domain: "thehindu.com", country: "India", url: "https://www.thehindu.com/news/national/feeder/default.rss" },
  { domain: "hindustantimes.com", country: "India", url: "https://www.hindustantimes.com/feeds/rss/world-news/rssfeed.xml" },
  { domain: "ndtv.com", country: "India", url: "https://feeds.feedburner.com/ndtvnews-world-news" },
  { domain: "timesofindia.indiatimes.com", country: "India", url: "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms" },
  { domain: "indianexpress.com", country: "India", url: "https://indianexpress.com/section/world/feed/" },
  { domain: "indiatoday.in", country: "India", url: "https://www.indiatoday.in/rss/1206577" },
  { domain: "economictimes.indiatimes.com", country: "India", url: "https://economictimes.indiatimes.com/news/international/rssfeeds/858478126.cms" },
  { domain: "firstpost.com", country: "India", url: "https://www.firstpost.com/commonfeeds/v1/mfp/rss/world.xml" },
  { domain: "news18.com", country: "India", url: "https://www.news18.com/rss/world.xml" },
  { domain: "dawn.com", country: "Pakistan", url: "https://www.dawn.com/feeds/home" },
  { domain: "tribune.com.pk", country: "Pakistan", url: "https://tribune.com.pk/feed/home" },
  { domain: "thenews.com.pk", country: "Pakistan", url: "https://www.thenews.com.pk/rss/1/1" },
  { domain: "geo.tv", country: "Pakistan", url: "https://www.geo.tv/rss/1/1" },
  { domain: "brecorder.com", country: "Pakistan", url: "https://www.brecorder.com/feeds/latest-news" },
  { domain: "thedailystar.net", country: "Bangladesh", url: "https://www.thedailystar.net/frontpage/rss.xml" },
  { domain: "kathmandupost.com", country: "Nepal", url: "https://kathmandupost.com/rss" },
  { domain: "tolonews.com", country: "Afghanistan", url: "https://tolonews.com/rss.xml" },
  { domain: "globaltimes.cn", country: "China", url: "https://www.globaltimes.cn/rss/outbrain.xml" },
  { domain: "xinhuanet.com", country: "China", url: "http://www.xinhuanet.com/english/rss/worldrss.xml" },
  { domain: "cgtn.com", country: "China", url: "https://www.cgtn.com/subscribe/rss/section/world.xml" },
  { domain: "scmp.com", country: "Hong Kong", url: "https://www.scmp.com/rss/91/feed" },
  { domain: "scmp.com", country: "Hong Kong", url: "https://www.scmp.com/rss/4/feed" },
  { domain: "koreatimes.co.kr", country: "South Korea", url: "https://www.koreatimes.co.kr/www/rss/world.xml" },
  { domain: "yna.co.kr", country: "South Korea", url: "https://en.yna.co.kr/RSS/news.xml" },
  { domain: "japantimes.co.jp", country: "Japan", url: "https://www.japantimes.co.jp/feed" },
  { domain: "nhk.or.jp", country: "Japan", url: "https://www3.nhk.or.jp/rss/news/cat6.xml" },
  { domain: "straitstimes.com", country: "Singapore", url: "https://www.straitstimes.com/news/world/rss.xml" },
  { domain: "straitstimes.com", country: "Singapore", url: "https://www.straitstimes.com/news/asia/rss.xml" },
  { domain: "channelnewsasia.com", country: "Singapore", url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml" },
  { domain: "philstar.com", country: "Philippines", url: "https://www.philstar.com/rss/headlines" },
  { domain: "inquirer.net", country: "Philippines", url: "https://www.inquirer.net/fullfeed" },
  { domain: "rappler.com", country: "Philippines", url: "https://www.rappler.com/feed/" },
  { domain: "manilatimes.net", country: "Philippines", url: "https://www.manilatimes.net/news/feed/" },
  { domain: "antaranews.com", country: "Indonesia", url: "https://en.antaranews.com/rss/world.xml" },
  { domain: "vnexpress.net", country: "Vietnam", url: "https://e.vnexpress.net/rss/news.rss" },
  { domain: "malaymail.com", country: "Malaysia", url: "https://www.malaymail.com/feed/rss/world" },
  { domain: "tass.com", country: "Russia", url: "https://tass.com/rss/v2.xml" },
  { domain: "rt.com", country: "Russia", url: "https://www.rt.com/rss/news/" },
  { domain: "themoscowtimes.com", country: "Russia", url: "https://www.themoscowtimes.com/rss/news" },
  { domain: "kyivindependent.com", country: "Ukraine", url: "https://kyivindependent.com/news-archive/rss/" },
  { domain: "ukrinform.net", country: "Ukraine", url: "https://www.ukrinform.net/rss/block-lastnews" },
  { domain: "euromaidanpress.com", country: "Ukraine", url: "https://euromaidanpress.com/feed/" },
  { domain: "dw.com", country: "Germany", url: "https://rss.dw.com/rdf/rss-en-all" },
  { domain: "rfi.fr", country: "France", url: "https://www.rfi.fr/en/rss" },
  { domain: "euronews.com", country: "France", url: "https://www.euronews.com/rss" },
  { domain: "politico.eu", country: "Belgium", url: "https://www.politico.eu/feed/" },
  { domain: "rte.ie", country: "Ireland", url: "https://www.rte.ie/news/rss/news-headlines.xml" },
  { domain: "notesfrompoland.com", country: "Poland", url: "https://notesfrompoland.com/feed/" },
  { domain: "dailymaverick.co.za", country: "South Africa", url: "https://www.dailymaverick.co.za/dmrss/" },
  { domain: "iol.co.za", country: "South Africa", url: "https://iol.co.za/rss/iol/news/world/" },
  { domain: "punchng.com", country: "Nigeria", url: "https://punchng.com/feed/" },
  { domain: "premiumtimesng.com", country: "Nigeria", url: "https://www.premiumtimesng.com/feed" },
  { domain: "vanguardngr.com", country: "Nigeria", url: "https://www.vanguardngr.com/feed/" },
  { domain: "allafrica.com", country: "Africa", url: "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf" },
  { domain: "africanews.com", country: "Africa", url: "https://www.africanews.com/feed/rss" },
  { domain: "mercopress.com", country: "Uruguay", url: "https://en.mercopress.com/rss" },
  { domain: "batimes.com.ar", country: "Argentina", url: "https://www.batimes.com.ar/feed" },
  { domain: "mexiconewsdaily.com", country: "Mexico", url: "https://mexiconewsdaily.com/feed/" },
  { domain: "riotimesonline.com", country: "Brazil", url: "https://www.riotimesonline.com/feed/" },
  { domain: "colombiareports.com", country: "Colombia", url: "https://colombiareports.com/feed/" },
  { domain: "venezuelanalysis.com", country: "Venezuela", url: "https://venezuelanalysis.com/feed" },
];
